[package]
name = "ERC4626"
version = "0.1.0"

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "841a073" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.10.2" }
starknet = ">=2.3.1"

[[target.starknet-contract]]
casm = true
